services:
  postgres:
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
